import {
  colorBrandBrown,
  colorBrandOrange,
  colorDarkGrey,
  colorMidGrey,
  colorWhite,
  freightBigPro,
  proximaNova,
} from '../../style';

const styles = {
  fourCardsWithPromptContainer: {
    display: 'flex',
    alignItems: {
      xs: 'flex-start',
      sm: 'flex-start',
      md: 'center',
    },
    justifyContent: 'center',
    margin: {
      xs: '0 0 0 0',
      sm: '0 0 0 0',
      md: '60px 0 0 0',
      lg: '80px 0 60px 0',
    },
    width: '100%',
    height: {
      xs: '100%',
      sm: '100%',
      md: '75vw',
      lg: '770px',
    },
    maxHeight: {
      xs: '100%',
      sm: '100%',
      md: '770px',
    },
  },
  fourCardsWithPromptContent: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'flex-start',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  fourCardsPromptContainer: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    marginBottom: {
      xs: '60px',
      sm: '60px',
      md: '0px',
    },
    width: {
      xs: '100%',
      sm: '100%',
      md: '50%',
    },
    height: {
      xs: '620px',
      sm: '620px',
      md: '100%',
    },
  },
  fourCardsPrompt: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    paddingTop: '20px',
    width: {
      xs: '100%',
      sm: '100%',
      md: '90%',
      lg: '85%',
      xl: '80%',
    },
    height: {
      xs: '100%',
      sm: '100%',
      md: '90%',
    },
    backgroundColor: '#F9F7F8',
  },
  fourCardsPromptInnerWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    flexDirection: 'column' as const,
    width: '80%',
    height: '100%',
  },
  fourCardsCards: {
    display: 'flex',
    alignItems: {
      xs: 'flex-start',
      sm: 'center',
    },
    justifyContent: {
      xs: 'space-evenly',
      sm: 'space-evenly',
      md: 'space-around',
      lg: 'space-between',
    },
    flexDirection: {
      xs: 'row' as const,
      sm: 'row' as const,
      md: 'row' as const,
      lg: 'column' as const,
    },
    flexWrap: 'wrap' as const,
    width: {
      xs: '100%',
      sm: '100%',
      md: '50%',
    },
    height: {
      xs: '120vw',
      sm: '810px',
      md: '100%',
    },
  },
  fourCardsCardContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'column' as const,
    marginBottom: {
      xs: '0',
      sm: '60px',
      md: '0',
    },
    width: '40%',
    height: {
      xs: 'auto',
      sm: '360px',
      md: '360px',
    },
    cursor: 'pointer',
  },
  fourCardsImage: {
    width: {
      xs: '40vw',
      sm: '40vw',
      md: '20vw',
    },
    maxWidth: '280px',
    height: {
      xs: '40vw',
      sm: '40vw',
      md: '20vw',
    },
    maxHeight: '280px',
    backgroundColor: colorWhite,
    backgroundSize: 'contain',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center center',
  },
  fourCardsPromptOverline: {
    color: colorBrandOrange,
    fontSize: '20px',
    fontFamily: freightBigPro,
    textAlign: 'center' as const,
  },
  fourCardsPromptTopline: {
    color: colorMidGrey,
    fontSize: '32px',
    fontFamily: freightBigPro,
    textAlign: 'center' as const,
  },
  fourCardsPromptBottomline: {
    color: colorBrandOrange,
    fontSize: {
      xs: '20px',
      sm: '28px',
      md: '28px',
    },
    fontFamily: freightBigPro,
    textAlign: 'center' as const,
  },
  fourCardsPromptParagraph: {
    color: colorDarkGrey,
    fontSize: '14px',
    fontFamily: proximaNova,
    textAlign: 'center' as const,
  },
  fourCardsPromptImage: {
    width: {
      xs: '250px',
      sm: '40vw',
      md: '30vw',
    },
    maxWidth: '350px',
    height: {
      xs: '250px',
      sm: '40vw',
      md: '30vw',
    },
    maxHeight: '350px',
    backgroundColor: colorWhite,
    backgroundSize: 'contain',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center center',
    borderRadius: '50%',
  },
  fourCardsPromptButton: {
    margin: '20px 0 40px 0',
    padding: '15px 50px',
    color: colorBrandBrown,
    backgroundColor: colorWhite,
    fontFamily: proximaNova,
    fontWeight: '100',
    fontSize: '1rem',
    textTransform: 'none' as const,
    borderWidth: '1px',
    borderColor: colorBrandBrown,
    borderRadius: 0,
    transition: 'all 0.25s ease',

    '&:hover': {
      color: colorWhite,
      backgroundColor: colorBrandBrown,
      borderWidth: '1px',
      borderColor: colorBrandBrown,
    },
  },
  fourCardsPromptButtonWrapper: {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
  },
  fourCardsLabelContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    marginTop: '15px',
    width: {
      xs: '40vw',
      sm: '40vw',
      md: '100%',
    },
    maxWidth: '280px',
  },
  fourCardsTitle: {
    fontSize: {
      xs: '3vw',
      sm: '1.25rem',
      md: '1.5vw',
      lg: '1.5vw',
    },
    fontFamily: proximaNova,
  },
  fourCardsSubtitle: {
    fontSize: {
      xs: '2.5vw',
      sm: '1rem',
      md: '1rem',
      lg: '1.25rem',
    },
    fontFamily: proximaNova,
  },
  fourCardSticker: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute' as const,
    marginTop: {
      xs: '-2%',
      sm: '-15px',
      md: '-1.5vw',
      lg: '-15px',
    },
    marginLeft: {
      xs: '37.5%',
      sm: '230px',
      md: '15vw',
      lg: '220px',
    },
    width: {
      xs: '40px',
      sm: '60px',
      md: '75px',
      lg: '86px',
    },
    height: {
      xs: '40px',
      sm: '60px',
      md: '75px',
      lg: '86px',
    },
    backgroundColor: colorWhite,
    borderRadius: '50%',
    filter: 'drop-shadow(0 0 5px #a3a2a2)',
    color: colorDarkGrey,
    fontFamily: proximaNova,
    fontSize: {
      xs: '12px',
      sm: '18px',
    },
  },
};

export default styles;
