// common styles for the whole project

export const colorBrandBlue = '#587DA9',
  colorBrandGreen = '#6AC283',
  colorBrandBrown = '#826C4F',
  colorBrandOrange = '#E56F4D',
  colorWhite = '#ffffff',
  colorBlack = '#000000',
  colorDarkGrey = '#333333',
  colorMidGrey = '#90949F',
  colorLightGrey = '#f7f7f7',
  freightBigPro = 'FreightBigPro',
  freightBigProSemibold = 'FreightBigProSemibold',
  freightBigProBookItalic = 'FreightBigProBookItalic',
  freightBigProMediumItalic = 'FreightBigProMediumItalic',
  frizQuadrata = 'FrizQuadrata',
  proximaNova = 'ProximaNovaRegular',
  proximaNovaThin = 'ProximaNovaThin',
  paddingMobile = '40px',
  siteMaxWidth = '400px';
